version: '3.3'
services:
  rmtp-server:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"  # Port cho RMTP
      - "8080:80"    # Port cho HTTP
    volumes:
      - ./data:/data  # Thư mục chia sẻ cho lưu trữ dữ liệu (chỉnh sửa đường dẫn nếu cần)
    networks:
      - rmtp_network
    restart: always

networks:
  rmtp_network: