version: "3.7"

services:
  app:
    ports:
      - 5001:5001
    command: server.py
    depends_on:
      - redis
    build:
      context: . 
    environment:
      SERVER_RTMP: "rtmp://10.10.11.39:1935"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81abc
    volumes:
      - .:/app
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81abc
